apiVersion: v1
kind: Service
metadata:
 name: django-webapp-backend

spec:
 selector: 
   app: backendwebapp

 ports:
  - name: http
    port: 80 
  - containerPort: 8001
    nodePort: 30080

 type: NodePort
